---
- name: Download artifact from Artifactory
  get_url:
    url: "{{ artifactory_host }}{{ artifact.artifact_path }}/{{ artifact.artifact_name }}"
    dest: "/tmp/{{ artifact.artifact_name }}"
    mode: '0440'

- name: Extract artifact
  unarchive:
    src: "/tmp/{{ artifact.artifact_name }}"
    dest: "/tmp"
    remote_src: yes

- name: Copy files to target folder
  command:
    cmd: "cp -r /tmp/{{ artifact.root_path }} {{ artifact.target_folder }}"

- name: Run whoami command
  command: whoami
  register: whoami_output
  become_user: user1

- name: Debug whoami output
  debug:
    var: whoami_output.stdout

- name: Run the script
  command: "{{ artifact.script_path }}"
  become_user: user1

- name: Clean up deployment
  file:
    path: "/tmp/{{ artifact.artifact_name }}"
    state: absent
